on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request. 
  push:
    branches:
      - main
      - pipeline
  pull_request:
      types: [opened, synchronize, reopened]
 
name: Main Workflow
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      with:
        args: >
          -Dsonar.projectKey=asi_key 
          -Dsonar.sources=. 
          -Dsonar.host.url=http://codequality.rintio.com 
          -Dsonar.login=279643047c893645f7e88ff2c532a7146b5826f9
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
